<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title> Vinculación Electoral </title>
	<link rel="icon" href="../public/imgs/favicon.png">
	<!-- <link rel="icon" href="../public/imgs/favicon.ico"> -->
	<link rel="stylesheet" href="<?php echo $url_css;?>bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $url_css;?>fontawesome-all.min.css">
	<link rel="stylesheet" href="<?php echo $url_css;?>custom.css">
	<link rel="stylesheet" href="<?php echo $url_css;?>jquery.dataTables.min.css">
	<link rel="stylesheet" href="<?php echo $url_css;?>estilos.css">
	<link rel="stylesheet" href="../public/icon/style.css">
	<link rel="stylesheet" href="../public/fonts/style.css">
	<link rel="stylesheet" href="../Docs form reg votantes/form_registro_votantes_files/formoid1/formoid-solid-blue.css">
	  <!-- <link rel="stylesheet" href="http://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css"> -->